# ##########################################################################
# Sonnne Battery
# ##########################################################################
- alias: Sonnen House Power Consumption per day
  trigger:
    platform: time
    at: '23:59:45'
  action:
  - service: notify.sonnen_house_consumption_today
    data_template:
      message: >
        {{ now().strftime('%d/%m/%Y') }},{{ states.sensor.sonnen_house_consumption_today.state }}

- alias: Sonnen Grid Feedin per day
  trigger:
    platform: time
    at: '23:59:45'
  action:
  - service: notify.sonnen_pv_gridfeedin_today
    data_template:
      message: >
        {{ now().strftime('%d/%m/%Y') }},{{ states.sensor.sonnen_pv_gridfeedin_today.state }}

- alias: Sonnen PV Production per day
  trigger:
    platform: time
    at: '23:59:45'
  action:
  - service: notify.sonnen_pv_production_today
    data_template:
      message: >
        {{ now().strftime('%d/%m/%Y') }},{{ states.sensor.sonnen_pv_production_today.state }}

- alias: Sonnen Inverter Power per day
  trigger:
    platform: time
    at: '23:59:45'
  action:
  - service: notify.sonnen_inverter_power_today
    data_template:
      message: >
        {{ now().strftime('%d/%m/%Y') }},{{ states.sensor.sonnen_inverter_power_today.state }}

# Sonnen House Power Consumption Reset
- alias: Sonnen House Power Consumption at start of the day
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_sonnen_house_consumption_previous
        value: "{{ states.sensor.sonnen_house_consumption_today.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_sonnen_house_consumption
        value: "{{ states.sensor.sensor_sonnen_house_consumption_integral.state }}"

- alias: Sonnen House Power Consumption hourly
  trigger:
    platform: time_pattern
    hours: /1
    minutes: 00
    seconds: 00
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.hourly_sonnen_house_consumption_previous
        value: "{{ states.sensor.sonnen_house_consumption_hour.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.hourly_sonnen_house_consumption
        value: "{{ states.sensor.sensor_sonnen_house_consumption_integral.state }}"

# Sonnen Grid Feedin Reset
- alias: Sonnen Grid Feedin at start of the day
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_sonnen_pv_gridfeedin_previous
        value: "{{ states.sensor.sonnen_pv_gridfeedin_today.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_sonnen_pv_gridfeedin
        value: "{{ states.sensor.sensor_sonnen_pv_gridfeedin_integral.state }}"

- alias: Sonnen Grid Feedin hourly
  trigger:
    platform: time_pattern
    hours: /1
    minutes: 00
    seconds: 00
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.hourly_sonnen_pv_gridfeedin_previous
        value: "{{ states.sensor.sonnen_pv_gridfeedin_hour.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.hourly_sonnen_pv_gridfeedin
        value: "{{ states.sensor.sensor_sonnen_pv_gridfeedin_integral.state }}"

# Sonnen Inverter Power Reset
- alias: Sonnen Inverter Power at start of the day
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_sonnen_inverter_power_previous
        value: "{{ states.sensor.sonnen_inverter_power_today.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_sonnen_inverter_power
        value: "{{ states.sensor.sensor_sonnen_inverter_power_integral.state }}"

- alias: Sonnen Inverter Power hourly
  trigger:
    platform: time_pattern
    hours: /1
    minutes: 00
    seconds: 00
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.hourly_sonnen_inverter_power_previous
        value: "{{ states.sensor.sonnen_inverter_power_hour.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.hourly_sonnen_inverter_power
        value: "{{ states.sensor.sensor_sonnen_inverter_power_integral.state }}"

# Sonnen PV Production Reset
- alias: Sonnen PV Production at start of the day
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_sonnen_pv_production_previous
        value: "{{ states.sensor.sonnen_pv_production_today.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_sonnen_pv_production
        value: "{{ states.sensor.sensor_sonnen_pv_production_integral.state }}"

- alias: Sonnen PV Production hourly
  trigger:
    platform: time_pattern
    hours: /1
    minutes: 00
    seconds: 00
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.hourly_sonnen_pv_production_previous
        value: "{{ states.sensor.sonnen_pv_production_hour.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.hourly_sonnen_pv_production
        value: "{{ states.sensor.sensor_sonnen_pv_production_integral.state }}"
