# Include automations
automation: !include automations.yaml

# Include input_numbers
input_number: !include input_numbers.yaml

# Include sensors
sensor: !include sensors.yaml

# Include notifiers
notify: !include notifiers.yaml

# Include utility meters
utility_meter: !include utility_meters.yaml
