- id: automation-0100
  alias: Camera Snapshot
  trigger:
  - entity_id: camera.aarlo_vorplatz,camera.aarlo_sudgarten,camera.aarlo_westgarten,camera.aarlo_nordgarten
    for: 00:00:03
    from: idle
    platform: state
    to: recording
  - entity_id: camera.aarlo_vorplatz,camera.aarlo_sudgarten,camera.aarlo_westgarten,camera.aarlo_nordgarten
    for: 00:00:03
    from: recently active
    platform: state
    to: recording
  condition: []
  action:
  - data_template:
      entity_id: '{{ trigger.entity_id }}'
    service: camera.aarlo_request_snapshot
  - data_template:
      filename: /config/www/aarlo.{{ trigger.entity_id }}.mp4
      entity_id: '{{ trigger.entity_id }}'
    service: camera.aarlo_request_video_to_file
  - data_template:
      filename: /config/www/aarlo.{{ trigger.entity_id }}.png
      entity_id: '{{ trigger.entity_id }}'
    service: camera.aarlo_request_snapshot_to_file
  - data_template:
      title: Motion Captured
      message: Video Capture on {{ trigger.entity_id }}
    service: notify.telegram
  - delay: 0:03
  - data_template:
      title: Send a Photo
      message: Photo Capture
      data:
        photo:
        - file: /config/www/aarlo.{{ trigger.entity_id }}.png
          caption: Camera Motion Photo {{ trigger.entity_id }}
    service: notify.telegram
  - delay: 0:30
  - data_template:
      title: Send a Video
      message: Video Capture
      data:
        video:
        - file: /config/www/aarlo.{{ trigger.entity_id }}.mp4
          caption: Camera Motion Video {{ trigger.entity_id }}
    service: notify.telegram
- alias: Washing Machine Running
  trigger:
  - platform: numeric_state
    entity_id: sensor.washing_machine_power
    above: 1000
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.washing_machine_status
      option: Running
- alias: Washing Machine Finished
  trigger:
  - platform: numeric_state
    entity_id: sensor.washing_machine_power
    below: 5
    for:
      minutes: 2
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.washing_machine_status
      state: Running
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.washing_machine_status
      option: Finished
- alias: Washing Maching Power Off
  trigger:
  - platform: numeric_state
    entity_id: sensor.washing_machine_power
    below: 0.2
    for:
      minutes: 2
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_select.washing_machine_status
      state: Finished
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.washing_machine_status
      option: PowerOff
- id: activate_startup_theme
  alias: Setze Theme beim Start
  initial_state: 'on'
  trigger:
  - platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: midnight_blue
- id: hyperion_activate_hdmi
  alias: Starte Hyperion Service beim Start
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: light.hyperion_service
    to: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.hyperion_service
      effect: HDMI
