- id: automation-0100
  alias: Camera Snapshot
  trigger:
  - entity_id: camera.aarlo_vorplatz,camera.aarlo_sudgarten,camera.aarlo_westgarten,camera.aarlo_nordgarten
    for: 00:00:03
    from: idle
    platform: state
    to: recording
  - entity_id: camera.aarlo_vorplatz,camera.aarlo_sudgarten,camera.aarlo_westgarten,camera.aarlo_nordgarten
    for: 00:00:03
    from: recently active
    platform: state
    to: recording
  condition: []
  action:
  - data_template:
      entity_id: '{{ trigger.entity_id }}'
    service: camera.aarlo_request_snapshot
  - data_template:
      filename: /config/www/aarlo.{{ trigger.entity_id }}.mp4
      entity_id: '{{ trigger.entity_id }}'
    service: camera.aarlo_request_video_to_file
  - data_template:
      filename: /config/www/aarlo.{{ trigger.entity_id }}.png
      entity_id: '{{ trigger.entity_id }}'
    service: camera.aarlo_request_snapshot_to_file
  - data_template:
      title: Send a Photo
      message: Photo Capture
      data:
        photo:
        - file: /config/www/aarlo.{{ trigger.entity_id }}.png
          caption: Camera Motion Photo {{ trigger.entity_id }}
    service: notify.telegram
  - delay: 00:01:30
  - data_template:
      title: Send a Video
      message: Video Capture
      data:
        video:
        - file: /config/www/aarlo.{{ trigger.entity_id }}.mp4
          caption: Camera Motion Video {{ trigger.entity_id }}
    service: notify.telegram
- id: dd3549e137c84ec2b884f6b6afd3d804
  alias: Washing Machine Running
  trigger:
  - above: '100'
    entity_id: sensor.washing_machine_power
    platform: numeric_state
  action:
  - data:
      option: running
    entity_id: input_select.washing_machine_status
    service: input_select.select_option
- id: 381011be494146e6899494f6749b59a1
  alias: Washing Machine Finished
  trigger:
  - below: '6'
    entity_id: sensor.washing_machine_power
    for: 0:01:00
    platform: numeric_state
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_select.washing_machine_status
      state: Running
  action:
  - data:
      entity_id: input_select.washing_machine_status
      option: Finished
    service: input_select.select_option
- id: e833fc7415ca4ed3b745cb3b0b108faf
  alias: Washing Maching Power Off
  trigger:
  - below: '1'
    entity_id: sensor.washing_machine_power
    for:
      minutes: 2
    platform: numeric_state
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_select.washing_machine_status
      state: Finished
  action:
  - data:
      entity_id: input_select.washing_machine_status
      option: PowerOff
    service: input_select.select_option
- id: '1584564050624'
  alias: Homematic Reconnect
  description: ''
  trigger:
  - entity_id: binary_sensor.homematic_up
    platform: state
    to: 'off'
  condition: []
  action:
  - data: {}
    service: homematic.reconnect
- id: '1586587531840'
  alias: Hyperion Service Start at Home Assistant Start
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  - entity_id: switch.hyperion_leds
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      effect: HDMI
    entity_id: light.hyperion_service
    service: light.turn_on
- id: '1586588042932'
  alias: Set Theme at Home Assistant Start
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: google_dark_theme
    service: frontend.set_theme
