# ##########################################################################
# Power Consumptions
# ##########################################################################
# Espresso Consumption
- alias: Espresso Machine Consumption Actual
  trigger:
    platform: time_pattern
    seconds: /10
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.continuous_espresso_machine_power
        value: "{{ states.sensor.espresso_power.state }}"

- alias: Espresso Machine Consumption at start of the day
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_espresso_machine_consumption_previous
        value: "{{ states.sensor.espresso_machine_consumption_today.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_espresso_machine_consumption
        value: "{{ states.sensor.input_number_continuous_espresso_machine_power_integral.state }}"

# Humidifier Consumption
- alias: Humidifier Consumption Actual
  trigger:
    platform: time_pattern
    seconds: /10
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.continuous_humidifier_power
        value: "{{ states.sensor.humidifier_power.state }}"

- alias: Humidifier Consumption at start of the day
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_humidifier_consumption_previous
        value: "{{ states.sensor.humidifier_consumption_today.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_humidifier_consumption
        value: "{{ states.sensor.input_number_continuous_humidifier_power_integral.state }}"

# Dehumidifier Consumption
- alias: Dehumidifier Consumption Actual
  trigger:
    platform: time_pattern
    seconds: /10
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.continuous_dehumidifier_power
        value: "{{ states.sensor.dehumidifier_power.state }}"

- alias: Dehumidifier Consumption at start of the day
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_dehumidifier_consumption_previous
        value: "{{ states.sensor.dehumidifier_consumption_today.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_dehumidifier_consumption
        value: "{{ states.sensor.input_number_continuous_dehumidifier_power_integral.state }}"

# Washing Machine Consumption
- alias: Washing Machine Consumption Actual
  trigger:
    platform: time_pattern
    seconds: /10
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.continuous_washing_machine_power
        value: "{{ states.sensor.washing_machine_power.state }}"

- alias: Washing Machine Consumption at start of the day
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_washing_machine_consumption_previous
        value: "{{ states.sensor.washing_machine_consumption_today.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_washing_machine_consumption
        value: "{{ states.sensor.input_number_continuous_washing_machine_power_integral.state }}"

# Dryer Consumption
- alias: Dryer Consumption Actual
  trigger:
    platform: time_pattern
    seconds: /10
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.continuous_dryer_power
        value: "{{ states.sensor.dryer_power.state }}"

- alias: Dryer Consumption at start of the day
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_dryer_consumption_previous
        value: "{{ states.sensor.dryer_consumption_today.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_dryer_consumption
        value: "{{ states.sensor.input_number_continuous_dryer_power_integral.state }}"

# Waterbed Consumption
- alias: Waterbed Consumption Actual
  trigger:
    platform: time_pattern
    seconds: /10
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.continuous_waterbed_power
        value: "{{ states.sensor.waterbed_power.state }}"

- alias: Waterbed Consumption at start of the day
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_waterbed_consumption_previous
        value: "{{ states.sensor.waterbed_consumption_today.state }}"
    - service: input_number.set_value
      data_template:
        entity_id: input_number.midnight_waterbed_consumption
        value: "{{ states.sensor.input_number_continuous_waterbed_power_integral.state }}"

# ##########################################################################
# Telegram
# ##########################################################################
#- id: telegramboot
#  alias: Benachrichtigung beim Start
#  trigger:
#    - platform: homeassistant
#      event: start
#  action:
#    - service: notify.telegram
#      data: Home Assistant ist gestartet

# ##########################################################################
# Arlo
# ##########################################################################
- id: 'automation-0100'
  alias: Camera Snapshot
  trigger:
  - entity_id: camera.aarlo_vorplatz,camera.aarlo_sudgarten,camera.aarlo_westgarten,camera.aarlo_nordgarten
    for: 00:00:03
    from: 'idle'
    platform: state
    to: 'recording'
  - entity_id: camera.aarlo_vorplatz,camera.aarlo_sudgarten,camera.aarlo_westgarten,camera.aarlo_nordgarten
    for: 00:00:03
    from: 'recently active'
    platform: state
    to: 'recording'
  condition: []
  action:
  - data_template:
      entity_id: "{{ trigger.entity_id }}"
    service: camera.aarlo_request_snapshot

# ##########################################################################
# Startup Theme
# ##########################################################################
- id: activate_startup_theme
  alias: Setze Theme beim Start
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: frontend.set_theme
    data:
      name: dark_theme

- id: hyperion_activate_hdmi
  alias: Starte Hyperion Service beim Start
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: light.hyperion
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hyperion_service
        effect: "HDMI"
