# ##########################################################################
# Homematic
# ##########################################################################
- platform: template
  sensors:
    homematic_up:
      friendly_name: "Homematic is sending updates"
      entity_id:
        - sensor.it_power
        - sensor.time
      value_template: >-
        {{as_timestamp(now()) - as_timestamp(states.sensor.it_power.last_changed) < 600}}

# ##########################################################################
# Arlo
# ##########################################################################
- platform: aarlo
  monitored_conditions:
  - motion
  - sound
  - ding

# ##########################################################################
# Test Internet Connection
# ##########################################################################
- platform: ping
  name: "Internet Connection"
  host: 8.8.8.8
  count: 2
  scan_interval: 30

# ##########################################################################
# Netatmo
# ##########################################################################
- platform: template
  sensors:
    netatmo_innenmodul_co2_high:
      friendly_name: "Wohnzimmer CO2"
      device_class: gas
      value_template: "{{ states('sensor.netatmo_innenmodul_co2')|int > 1500 }}"
    netatmo_innenmodul_humidity_high:
      friendly_name: "Wohnzimmer Luftfeuchtigkeit"
      device_class: moisture
      value_template: "{{ states('sensor.netatmo_innenmodul_humidity')|int > 60 }}"


# ##########################################################################
# APC UPS
# ##########################################################################
- platform: apcupsd

# ##########################################################################
# Air Dehumidifier
# ##########################################################################
- platform: template
  sensors:
    dehumidifier_active:
      friendly_name: "Luftentfeuchter l채uft"
      device_class: power
      delay_off:
        minutes: 5
      value_template: "{{ states('sensor.dehumidifier_power')|float > 10 }}"

# ##########################################################################
# Espresso
# ##########################################################################
- platform: template
  sensors:
    espresso_heating_up:
      friendly_name: "Espresso heizt"
      device_class: power
      delay_off:
        minutes: 1
      value_template: "{{ states('sensor.espresso_power')|float > 10 }}"

# ##########################################################################
# Air Humidifier
# ##########################################################################
- platform: template
  sensors:
    humidifier_active:
      friendly_name: "Luftbefeuchter l채uft"
      device_class: power
      value_template: "{{ states('sensor.humidifier_power')|float > 10 }}"

# ##########################################################################
# Washing Machine & Dryer
# ##########################################################################
- platform: template
  sensors:
    washing_machine_active:
      friendly_name: "Waschmaschine l채uft"
      device_class: power
      delay_off:
        minutes: 5
      value_template: "{{ states('sensor.washing_machine_power')|float > 10 }}"
- platform: template
  sensors:
    dryer_active:
      friendly_name: "Trockner l채uft"
      device_class: power
      delay_off:
        minutes: 15
      value_template: "{{ states('sensor.dryer_power')|float > 10 }}"

# ##########################################################################
# Bayesian Binary Sensor
# ##########################################################################
- platform: bayesian
  prior: 0.5
  name: 'Markus Presence'
  probability_threshold: 0.8
  observations:
    - entity_id: 'device_tracker.markus_nodered'
      prob_given_true: 0.8
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.markus_iphone_11_gps'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.markus_owntracks'
      prob_given_true: 0.9
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.markus_ping'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'

- platform: bayesian
  prior: 0.5
  name: 'Magda Presence'
  probability_threshold: 0.8
  observations:
    - entity_id: 'device_tracker.magda_nodered'
      prob_given_true: 0.8
      prob_given_false: 0.2
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.magda_iphone_8_gps'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.magda_owntracks'
      prob_given_true: 0.9
      prob_given_false: 0.4
      platform: 'state'
      to_state: 'home'
    - entity_id: 'device_tracker.magda_ping'
      prob_given_true: 0.9
      prob_given_false: 0.1
      platform: 'state'
      to_state: 'home'
