homeassistant:
  # Name of the location where Home Assistant is running
  name: Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret zone_home_elevation

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  # Customization file
  customize: !include customize.yaml

  # Include packages
  packages:
    pack_mower: !include packages/mower/package.yaml
    pack_sonnen: !include packages/sonnen/package.yaml
    pack_zigbee: !include packages/zigbee/package.yaml
    # pack_battery_alert: !include packages/battery_alert/battery_alert.yaml

  whitelist_external_dirs:
    - /tmp
    - /config/www

logger:
  default: info
#  logs:
#    custom_components.alexa_media: debug

recorder:
  purge_keep_days: 31
  purge_interval: 1
  db_url: !secret homeassistantdb

# Sets kown zones
zone:
  - name: home
    latitude: !secret zone_home_latitude
    longitude: !secret zone_home_longitude
    radius: 25

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/
  javascript_version: latest

# Enable the mobile app companion
mobile_app:

# Enable system health
system_health:

# Enables configuration UI
config:

# Enable http
http:

# Enables the api
api:

# ##########################################################################
# Enable central functionalities and network connections
# ##########################################################################
# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Connect to InfluxDB
influxdb:
  host: !secret influxdb_ip
  database: home_assistant
  tags:
    source: hass

# Connect to network MQTT
mqtt:
  broker: !secret mqtt_ip
  port: !secret mqtt_port
  client_id: homeassistant
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'homeassistant/status'
    payload: 'online'
  will_message:
    topic: 'homeassistant/status'
    payload: 'offline'

# Integrate Panel
panel_iframe:
  nodered:
    title: 'Node-Red'
    icon: 'mdi:shuffle-variant'
    url: !secret nodered_url
  jupyterlab:
    title: JupyterLab
    url: !secret jupyterlab_url
    icon: mdi:database-search

# ##########################################################################
# Enable cloud connections
# ##########################################################################
# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Netatmo
netatmo:
  client_id: !secret netatmo_api_key
  client_secret: !secret netatmo_secret

# Include SolarEdge
solaredge:
  api_key: !secret solaredge_api_key
  site_id: !secret solaredge_site_id

# Gardena
gardena:
  username : !secret gardena_user
  password : !secret gardena_password

# Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    parse_mode: html
    allowed_chat_ids:
      - !secret telegram_chat_id

# Include Calendar
#calendar:
#  - platform: caldav
#    url: https://caldav.icloud.com
#    username: !secret icloud_username
#    password: !secret icloud_password
#    calendars:
##      - 'Calendar Name'

# Ring
ring:
  username: !secret ring_username
  password: !secret ring_password

# Weather
weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key

# ##########################################################################
# Include sub config files
# ##########################################################################

# Include automation scripts
automation: !include automations.yaml

# Include binary sensors
binary_sensor: !include binary_sensors.yaml

# Include cameras
camera: !include camera.yaml

# Enable home assistant cloud
cloud: !include cloud.yaml

# Activates device trackers
device_tracker: !include device_trackers.yaml

# Include group definitions
group: !include groups.yaml

# Include input booleans
input_boolean: !include input_booleans.yaml

# Include input numbers
input_number: !include input_numbers.yaml

# Include input selects
input_select: !include input_selects.yaml

# Include input texts
input_text: !include input_texts.yaml

# Include intent scripts
intent_script: !include intents.yaml

# Include iOS
ios: !include ios.yaml

# Include lights
light: !include lights.yaml

# Include media players
media_player: !include media_players.yaml

# Include notifiers
notify: !include notifiers.yaml

# Scenes
scene: !include scenes.yaml

# Include scripts
script: !include scripts.yaml

# Include sensors
sensor: !include sensors.yaml

# Include switches
switch: !include switches.yaml

# Include timer
timer: !include timers.yaml

# Include utility meters
utility_meter: !include utility_meters.yaml

# ##########################################################################
# Configure some domains
# ##########################################################################
# Include Harmony
remote:
  - platform: harmony
    name: living_room
    host: !secret harmony_ip

homekit:
  filter:
    include_domains:
      - alarm_control_panel
      - light
      - media_player
      - switch
      - lock
      - cover

apcupsd:
  host: 192.168.1.115

# Include Alexa
alexa_media:
  accounts:
    - email: !secret amazon_email
      password: !secret amazon_password
      url: amazon.de

homematic:
  interfaces:
    rf:
      host: !secret homematic_ip
    ip:
      host: !secret homematic_ip
      port: 2010
    groups:
      host: !secret homematic_ip
      port: 9292
      username: !secret homematic_username
      password: !secret homematic_password
      path: /groups
      resolvenames: json
  hosts:
    ccu3:
      host: !secret homematic_ip
      username: !secret homematic_username
      password: !secret homematic_password

webostv:
  host: !secret webostv_ip
  name: LG TV
  turn_on_action:
    service: wake_on_lan.send_magic_packet
    data:
      mac: !secret webostv_mac

#alert:
#  cam1_motion:
#    name: Cam1 detected motion
#    entity_id: binary_sensor.motion_sensor_158d000200b808
#    # entity_id: binary_sensor.cam_1_dafang_motion_sensor
#    state: 'on'
#    #repeat: 1
#    notifiers:
#      - notify.telegram

# Arlo Cameras
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  packet_dump: True
  db_motion_time: 30
  db_ding_time: 10
  recent_time: 10
  last_format: '%m-%d %H:%M'
  conf_dir: /config/.aarlo
  no_media_upload: True
  mode_api: auto
  refresh_devices_every: 0
  http_connections: 5
  http_max_size: 10

alarm_control_panel:
  - platform: aarlo
    home_mode_name: home
    away_mode_name: armed
    trigger_time: 30
    alarm_volume: 8

#arlo:
#  username: !secret arlo_username
#  password: !secret arlo_password

#alarm_control_panel:
#  - platform: arlo

# Include Stream
stream:
