homeassistant:
  # Name of the location where Home Assistant is running
  name: Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret zone_home_latitude
  longitude: !secret zone_home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret zone_home_elevation

  # metric for Metric, imperial for Imperial
  unit_system: metric

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  # Customization file
  customize: !include customize.yaml

  # Include packages
  packages:
    pack_sonnen: !include packages/sonnen/package.yaml

logger:
  default: info
#  logs:
#    custom_components.alexa_media: debug

recorder:
  purge_keep_days: 90
  purge_interval: 1
  db_url: !secret homeassistantdb

# Sets kown zones
zone:
  - name: home
    latitude: !secret zone_home_latitude
    longitude: !secret zone_home_longitude
    radius: 25

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/
  javascript_version: latest

# Enable the mobile app companion
mobile_app:

# Enable system health
system_health:

#lovelace:
#  mode: yaml

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
#  trusted_networks:
#    - 127.0.0.1
#    - ::1
#  ip_ban_enabled: True
#  login_attempts_threshold: 5

# Enables the api
api:

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true


# ##########################################################################
# Enable central functionalities and network connections
# ##########################################################################
# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Connect to InfluxDB
influxdb:
  host: !secret influxdb_ip
  database: home_assistant
  tags:
    source: hass

# Connect to network MQTT
mqtt:
  broker: !secret mqtt_ip
  port: !secret mqtt_port
  client_id: homeassistant
  discovery: true
  discovery_prefix: homeassistant
  birth_message:
    topic: 'homeassistant/status'
    payload: 'online'
  will_message:
    topic: 'homeassistant/status'
    payload: 'offline'

# Integrate Node-Red, Jupyter and States in panel
panel_iframe:
  nodered:
    title: 'Node-Red'
    icon: 'mdi:shuffle-variant'
    url: !secret nodered_url
  jupyterlab:
    title: JupyterLab
    url: !secret jupyterlab_url  # URL GOES HERE
    icon: mdi:database-search
  grafana:
    title: Grafana
    url: http://192.168.1.115:3000
    icon: mdi:chart-histogram
  states_view:
    title: 'States'
    icon: 'mdi:power-socket-us'
    url: !secret states_view_url
  networkmap:
    title: 'Zigbee Map'
    url: '/local/zigbee2mqtt_networkmap/map.html'
    icon: 'mdi:graphql'

# ##########################################################################
# Enable cloud connections
# ##########################################################################
# Enable home assistant cloud
cloud: !include cloud.yaml

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret
  username: !secret netatmo_login_id
  password: !secret netatmo_password
  discovery: true

# ##########################################################################
# Include sub config files
# ##########################################################################
# Scenes
scene: !include scenes.yaml

# Activates device trackers
device_tracker: !include device_trackers.yaml

# Include sensors
sensor: !include sensors.yaml

# Include binary sensors
binary_sensor: !include binary_sensors.yaml

# Include utility meters
utility_meter: !include utility_meters.yaml

# Include input booleans
input_boolean: !include input_booleans.yaml

# Include input numbers
input_number: !include input_numbers.yaml

# Include input texts
input_text: !include input_texts.yaml

# Include notifiers
notify: !include notifiers.yaml

# Include timer
timer: !include timers.yaml

# Include switches
switch: !include switches.yaml

# Include group definitions
group: !include groups.yaml

# Include automation scripts
automation: !include automations.yaml

# Include scripts
script: !include scripts.yaml

# Include media players
media_player: !include media_players.yaml

# Include iOS
ios: !include ios.yaml

# Include input selects
input_select: !include input_selects.yaml

# Include intent scripts
intent_script: !include intents.yaml

# Include lights
light: !include lights.yaml

# Include cameras
camera: !include camera.yaml

# Include Calendar
calendar:
  - platform: caldav
    url: https://caldav.icloud.com
    username: !secret icloud_username
    password: !secret icloud_password
    calendars:
#      - 'Calendar Name'

stream:

# Include Harmony
remote:
  - platform: harmony
    name: living_room
    host: !secret harmony_ip

# Include SolarEdge
solaredge:
  api_key: !secret solaredge_api_key
  site_id: !secret solaredge_site_id

# Zigbee Network Map
webhook:
zigbee2mqtt_networkmap:

# ##########################################################################
# Configure some special devices
# ##########################################################################
#apple_tv:
#  - host: !secret apple_tv_3_ip
#    login_id: !secret apple_tv_3_login_id
#    name: Apple TV 3
##    start_off: true
#    credentials: !secret apple_tv_3_credential
#  - host: !secret apple_tv_4_ip
#    login_id: !secret apple_tv_4_login_id
#    name: Apple TV 4
#    start_off: true
#    credentials: !secret apple_tv_4_credential

homekit:
  filter:
    include_domains:
      - light

climate:
  - platform: netatmo

apcupsd:
  host: 192.168.1.115

hacs:
  token: !secret hacs_token


# Include Alexa
alexa_media:
  accounts:
    - email: !secret amazon_email
      password: !secret amazon_password
      url: amazon.de

#example_sensor: # testing
gardena:
  username : !secret gardena_user
  password : !secret gardena_password

#xiaomi_aqara:
#  discovery_retry: 5
#  gateways:
#    - mac: !secret xiaomi_aqara_mac
#      key: !secret xiaomi_aqara_key

#homematicip_cloud:
#  accesspoint: !secret homematicip_accesspoint
#  authtoken: !secret homematicip_authtoken

homematic:
  interfaces:
    rf:
      host: !secret homematic_ip
    ip:
      host: !secret homematic_ip
      port: 2010
    groups:
      host: !secret homematic_ip
      port: 9292
      username: !secret homematic_username
      password: !secret homematic_password
      path: /groups
      resolvenames: json
  hosts:
    ccu3:
      host: !secret homematic_ip
      username: !secret homematic_username
      password: !secret homematic_password

#hue:
#  bridges:
#    -host: bridge1_ip
#     filename: phue1.conf
#    -host: bridge2_ip
#     filename: phue2.conf

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

#alert:
#  cam1_motion:
#    name: Cam1 detected motion
#    entity_id: binary_sensor.motion_sensor_158d000200b808
#    # entity_id: binary_sensor.cam_1_dafang_motion_sensor
#    state: 'on'
#    #repeat: 1
#    notifiers:
#      - notify.telegram

#arlo:
#  username: !secret arlo_username
#  password: !secret arlo_password

#alarm_control_panel:
#  - platform: arlo

aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  packet_dump: True
  db_motion_time: 30
  db_ding_time: 10
  recent_time: 10
  last_format: '%m-%d %H:%M'
  conf_dir: /config/.aarlo
  no_media_upload: True
  mode_api: auto
  refresh_devices_every: 0
  http_connections: 5
  http_max_size: 10

alarm_control_panel:
  - platform: aarlo
    home_mode_name: home
    away_mode_name: armed
    trigger_time: 30
    alarm_volume: 8

ring:
  username: !secret ring_username
  password: !secret ring_password

# Only in Lovelace YAML mode :-(
#custom_updater:
#  track:
#    - cards
#    - components
#  card_urls:
#    - https://raw.githubusercontent.com/bramkragten/custom-ui/master/updater.json
#    - https://raw.githubusercontent.com/nervetattoo/simple-thermostat/master/tracker.json

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key
