# ##########################################################################
# Bluetooth
# ##########################################################################
#- platform: bluetooth_tracker

# ##########################################################################
# Nmap
# ##########################################################################
- platform: nmap_tracker
  hosts:
    - 192.168.1.78
    - 192.168.1.82
  interval_seconds: 30
  home_interval: 10
  scan_options: " --privileged -sP "
  consider_home: 1800
  new_device_defaults:
    track_new_devices: false

# ##########################################################################
# Unifi
# ##########################################################################
#- platform: unifi
#  host: !secret unifi_controller
#  username: !secret unifi_username
#  password: !secret unifi_password
#  verify_ssl: false
#  ssid_filter:
#    - 'Holonet'

# ##########################################################################
# Ping
# ##########################################################################
- platform: ping
  hosts:
    markus_ping: 192.168.1.82
    magda_ping: 192.168.1.78
