# ##########################################################################
# Switch Transforms
# ##########################################################################
- platform: switch
  name: living_room_showcase
  entity_id: switch.living_room_showcase

- platform: switch
  name: kitchen_tetris
  entity_id: switch.kitchen_tetris

# ##########################################################################
# Rooms - Link to Alexa Groups
# ##########################################################################
- platform: group
  name: Flur
  entities:
    - light.entrance_ceiling_light_1
    - light.entrance_ceiling_light_2

- platform: group
  name: Küche
  entities:
    - light.kitchen_counter_top_north
    - light.kitchen_dining_table_light_up
    - light.kitchen_dining_table_light_down
    - light.kitchen_ceiling_light
    - light.switch_kitchen_tetris

- platform: group
  name: Wohnzimmer
  entities:
    - light.living_room_color_floor_lamp_candle_1
    - light.living_room_color_floor_lamp_candle_2
    - light.living_room_color_floor_lamp_candle_3
    - light.living_room_iris
    - light.living_room_play_1
    - light.living_room_play_2
    - light.living_room_wall_lamp
    - light.living_room_table_lamp
    - light.living_room_heart
    - light.xmas_star

- platform: group
  name: Wohnzimmer Farbstehlampe
  entities:
    - light.living_room_color_floor_lamp_candle_1
    - light.living_room_color_floor_lamp_candle_2
    - light.living_room_color_floor_lamp_candle_3

- platform: group
  name: Toilette
  entities:
    - light.toilet_ceiling_light

- platform: group
  name: Amelie
  entities:
    - light.kidsroom_amelie_ceiling_light
    - light.kidsroom_amelie_globe

- platform: group
  name: Marlene
  entities:
    - light.kidsroom_marlene_wall_lamp

- platform: group
  name: Schlafzimmer
  entities:
    - light.bedroom_ceiling_light
    - light.bedroom_wardrobe
    - light.bedroom_wall_lamp

- platform: group
  name: Badezimmer
  entities:
    - light.bathroom_mirror
    - light.bathroom_ceiling_light

- platform: group
  name: Studio
  entities:
    - light.studio_ceiling_light_1
    - light.studio_ceiling_light_2
    - light.studio_desk_lamp
    - light.switch_studio_floor_lamp_1
    - light.switch_studio_floor_lamp_2
    - light.studio_iris
    - light.switch_studio_showcase
    - light.studio_sofa

- platform: group
  name: Fitness
  entities:
    - light.fitness_ceiling_light_1
    - light.fitness_ceiling_light_2
    - light.fitness_pillar_1
    - light.fitness_pillar_2

#- platform: stairs
#  name: stairs_group
#  entities:

- platform: group
  name: Garten
  entities:
    - light.garden_south

# ##########################################################################
# Misc
# ##########################################################################
- platform: hyperion
  host: !secret hyperion_ip
  name: Hyperion Service
  effect_list:
    - 'HDMI'
    - 'Warm mood blobs'
    - 'Rainbow mood'
    - 'Rainbow swirl'
    - ‘UDP multicast listener’
    - ‘UDP listener’
