#- platform: apple_tv
#  - host: !secret apple_tv_3_ip
#    login_id: !secret apple_tv_3_login_id
#    name: Apple TV 3
##    start_off: true
#    credentials: !secret apple_tv_3_credential
#  - host: !secret apple_tv_4_ip
#    login_id: !secret apple_tv_4_login_id
#    name: Apple TV 4
#    start_off: true
#    credentials: !secret apple_tv_4_credential

# - platform: webostv
#   host: !secret webostv_ip
#   name: LG OLED65C7D
#   timeout: 5

- platform: onkyo
  host: 192.168.1.97
  name: Receiver

# - platform: pioneer
#   host: 192.168.1.97
#   port: 8102
#   name: VSX-1131
