# ##########################################################################
# Zigbee Networkmap
# ##########################################################################
- id: update_networkmap
  alias: 'Zigbee Map aktualisieren'
  hide_entity: true
  trigger:
    platform: time_pattern
    minutes: '/10'
    seconds: 00
  action:
    service: zigbee2mqtt_networkmap.update

# ##########################################################################
# Zigbee2mqtt
# ##########################################################################
- alias: Zigbee2mqtt1 Log Level
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.zigbee2mqtt1_log_level
      to: debug
    - platform: state
      entity_id: input_select.zigbee2mqtt1_log_level
      to: warn
    - platform: state
      entity_id: input_select.zigbee2mqtt1_log_level
      to: error
    - platform: state
      entity_id: input_select.zigbee2mqtt1_log_level
      to: info
  action:
    - service: mqtt.publish
      data:
        payload_template: '{{ states(''input_select.zigbee2mqtt1_log_level'') }}'
        topic: zigbee2mqtt1/bridge/config/log_level
- alias: Zigbee2mqtt2 Log Level
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.zigbee2mqtt2_log_level
      to: debug
    - platform: state
      entity_id: input_select.zigbee2mqtt2_log_level
      to: warn
    - platform: state
      entity_id: input_select.zigbee2mqtt2_log_level
      to: error
    - platform: state
      entity_id: input_select.zigbee2mqtt2_log_level
      to: info
  action:
    - service: mqtt.publish
      data:
        payload_template: '{{ states(''input_select.zigbee2mqtt2_log_level'') }}'
        topic: zigbee2mqtt2/bridge/config/log_level

- id: enable_zigbee1_join
  alias: Enable Zigbee1 joining
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_boolean.zigbee1_permit_join
    to: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt1/bridge/config/permit_join
      payload: 'true'
  - service: timer.start
    data:
      entity_id: timer.zigbee1_permit_join
- id: enable_zigbee2_join
  alias: Enable Zigbee2 joining
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_boolean.zigbee2_permit_join
    to: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt2/bridge/config/permit_join
      payload: 'true'
  - service: timer.start
    data:
      entity_id: timer.zigbee2_permit_join

- id: disable_zigbee1_join
  alias: Disable Zigbee1 joining
  hide_entity: true
  trigger:
  - entity_id: input_boolean.zigbee1_permit_join
    platform: state
    to: 'off'
  action:
  - data:
      payload: 'false'
      topic: zigbee2mqtt1/bridge/config/permit_join
    service: mqtt.publish
  - data:
      entity_id: timer.zigbee1_permit_join
    service: timer.cancel
- id: disable_zigbee2_join
  alias: Disable Zigbee2 joining
  hide_entity: true
  trigger:
  - entity_id: input_boolean.zigbee2_permit_join
    platform: state
    to: 'off'
  action:
  - data:
      payload: 'false'
      topic: zigbee2mqtt2/bridge/config/permit_join
    service: mqtt.publish
  - data:
      entity_id: timer.zigbee2_permit_join
    service: timer.cancel

- id: disable_zigbee1_join_timer
  alias: Disable Zigbee1 joining by timer
  hide_entity: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee1_permit_join
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt1/bridge/config/permit_join
      payload: 'false'
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.zigbee1_permit_join
- id: disable_zigbee2_join_timer
  alias: Disable Zigbee2 joining by timer
  hide_entity: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee2_permit_join
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt2/bridge/config/permit_join
      payload: 'false'
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.zigbee2_permit_join
