# ##########################################################################
# Zigbee Bridge State
# ##########################################################################
# Sensor for monitoring the bridge state
- platform: mqtt
  name: Zigbee2mqtt1 Bridge state
  state_topic: "zigbee2mqtt1/bridge/state"
  icon: mdi:router-wireless
# Sensor for Showing the Zigbee2mqtt Version
- platform: mqtt
  name: Zigbee2mqtt1 Version
  state_topic: "zigbee2mqtt1/bridge/config"
  value_template: "{{ value_json.version }}"
  icon: mdi:zigbee
# Sensor for Showing the Coordinator Version
- platform: mqtt
  name: Coordinator1 Version
  state_topic: "zigbee2mqtt1/bridge/config"
  value_template: "{{ value_json.coordinator }}"
  icon: mdi:chip

# Sensor for monitoring the bridge state
- platform: mqtt
  name: Zigbee2mqtt2 Bridge state
  state_topic: "zigbee2mqtt2/bridge/state"
  icon: mdi:router-wireless
# Sensor for Showing the Zigbee2mqtt Version
- platform: mqtt
  name: Zigbee2mqtt2 Version
  state_topic: "zigbee2mqtt2/bridge/config"
  value_template: "{{ value_json.version }}"
  icon: mdi:zigbee
# Sensor for Showing the Coordinator Version
- platform: mqtt
  name: Coordinator2 Version
  state_topic: "zigbee2mqtt2/bridge/config"
  value_template: "{{ value_json.coordinator }}"
  icon: mdi:chip
