# ##########################################################################
# Zigbee2mqtt
# ##########################################################################
- platform: mqtt
  name: "Zigbee2mqtt1 Main join"
  state_topic: "zigbee2mqtt1/bridge/config/permit_join"
  command_topic: "zigbee2mqtt1/bridge/config/permit_join"
  payload_on: "true"
  payload_off: "false"

- platform: mqtt
  name: "Zigbee2mqtt2 Main join"
  state_topic: "zigbee2mqtt2/bridge/config/permit_join"
  command_topic: "zigbee2mqtt2/bridge/config/permit_join"
  payload_on: "true"
  payload_off: "false"
