# ##########################################################################
# Telegram
# ##########################################################################
#- id: telegramboot
#  alias: Benachrichtigung beim Start
#  trigger:
#    - platform: homeassistant
#      event: start
#  action:
#    - service: notify.telegram
#      data: Home Assistant ist gestartet

# ##########################################################################
# Startup Theme
# ##########################################################################
- id: activate_startup_theme
  alias: Setze Theme beim Start
  initial_state: 'on'
  trigger:
    - platform: homeassistant
      event: start
  action:
    service: frontend.set_theme
    data:
      name: dark_theme

- id: hyperion_activate_hdmi
  alias: Starte Hyperion Service beim Start
  trigger:
    - platform: homeassistant
      event: start
#    - platform: state
#      entity_id: light.hyperion
#      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.hyperion_service
        effect: "HDMI"

# ##########################################################################
# Zigbee
# ##########################################################################
- alias: Zigbee2mqtt Log Level
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: input_select.zigbee2mqtt_log_level
      to: debug
    - platform: state
      entity_id: input_select.zigbee2mqtt_log_level
      to: warn
    - platform: state
      entity_id: input_select.zigbee2mqtt_log_level
      to: error
    - platform: state
      entity_id: input_select.zigbee2mqtt_log_level
      to: info
  action:
    - service: mqtt.publish
      data:
        payload_template: '{{ states(''input_select.zigbee2mqtt_log_level'') }}'
        topic: zigbee2mqtt/bridge/config/log_level

- id: enable_zigbee_join
  alias: Enable Zigbee joining
  hide_entity: true
  trigger:
    platform: state
    entity_id: input_boolean.zigbee_permit_join
    to: 'on'
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'true'
  - service: timer.start
    data:
      entity_id: timer.zigbee_permit_join

- id: disable_zigbee_join
  alias: Disable Zigbee joining
  hide_entity: true
  trigger:
  - entity_id: input_boolean.zigbee_permit_join
    platform: state
    to: 'off'
  action:
  - data:
      payload: 'false'
      topic: zigbee2mqtt/bridge/config/permit_join
    service: mqtt.publish
  - data:
      entity_id: timer.zigbee_permit_join
    service: timer.cancel

- id: disable_zigbee_join_timer
  alias: Disable Zigbee joining by timer
  hide_entity: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee_permit_join
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'false'
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.zigbee_permit_join
