# ##########################################################################
# Arlo
# ##########################################################################
- platform: arlo
#  ffmpeg_arguments: '-pred 1 -q:v 2'

# ##########################################################################
# Ring
# ##########################################################################
- platform: ring
#  ffmpeg_arguments: '-pred 1 -q:v 2'

# ##########################################################################
# Ffmpeg
# ##########################################################################
#- platform: ffmpeg
#  name: Cam 1 Dafang
#  input: -rtsp_transport tcp -i rtsp://192.168.1.200:8554/unicast
