#- platform: plex
##  host: !secret plex_ip
##  port: !secret plex_port
#  entity_namespace: plex
#  include_non_clients: false
#  scan_interval: 1
#  show_all_controls: false
#  use_custom_entity_ids: false
#  use_episode_art: true
#  remote_unavailable_clients: false

- platform: webostv
  host: !secret webostv_ip
  name: LG OLED65C7D
  timeout: 5

#- platform: onkyo

#- platform: pioneer
#  host: 192.168.1.97
#  port: 8102
#  name: VSX-1131

#- platform: alexa
#  email: !secret amazon_email
#  password: !secret amazon_password
#  url: amazon.de

#- platform: alexa_media
#  accounts:
#    - email: !secret amazon_email
#      password: !secret amazon_password
#      url: amazon.de
