# ##########################################################################
# System Monitor
# ##########################################################################
#- platform: systemmonitor
#  resources:
#    - type: disk_use_percent
#      arg: /
#    - type: disk_use
#    - type: disk_free
#    - type: memory_use_percent
#    - type: memory_use
#    - type: memory_free
#    - type: load_1m
#    - type: load_5m
#    - type: load_15m
#    - type: network_in
#    - type: network_out
#    - type: processor_use
#    - type: last_boot

- platform: glances
  host: 192.168.1.115
  name: SmartHome
  version: 3
  resources:
    - disk_use_percent
    - disk_use
    - disk_free
    - memory_use_percent
    - memory_use
    - memory_free
    - swap_use_percent
    - swap_use
    - swap_free
    - processor_load
    - process_running
    - process_total
    - process_thread
    - process_sleeping
#    - cpu_use_percent
    - cpu_temp
    - docker_active
    - docker_cpu_use
    - docker_memory_use

- platform: glances
  host: 192.168.1.150
  name: K8s Master
  version: 3
  resources:
    - disk_use_percent
    - disk_use
    - disk_free
    - memory_use_percent
    - memory_use
    - memory_free
    - swap_use_percent
    - swap_use
    - swap_free
    - processor_load
    - process_running
    - process_total
    - process_thread
    - process_sleeping
#    - cpu_use_percent
    - cpu_temp
    - docker_active
    - docker_cpu_use
    - docker_memory_use

- platform: glances
  host: 192.168.1.151
  name: K8s Worker 1
  version: 3
  resources:
    - disk_use_percent
    - disk_use
    - disk_free
    - memory_use_percent
    - memory_use
    - memory_free
    - swap_use_percent
    - swap_use
    - swap_free
    - processor_load
    - process_running
    - process_total
    - process_thread
    - process_sleeping
#    - cpu_use_percent
    - cpu_temp
    - docker_active
    - docker_cpu_use
    - docker_memory_use

- platform: glances
  host: 192.168.1.152
  name: K8s Worker 2
  version: 3
  resources:
    - disk_use_percent
    - disk_use
    - disk_free
    - memory_use_percent
    - memory_use
    - memory_free
    - swap_use_percent
    - swap_use
    - swap_free
    - processor_load
    - process_running
    - process_total
    - process_thread
    - process_sleeping
#    - cpu_use_percent
    - cpu_temp
    - docker_active
    - docker_cpu_use
    - docker_memory_use

- platform: glances
  host: 192.168.1.153
  name: K8s Worker 3
  version: 3
  resources:
    - disk_use_percent
    - disk_use
    - disk_free
    - memory_use_percent
    - memory_use
    - memory_free
    - swap_use_percent
    - swap_use
    - swap_free
    - processor_load
    - process_running
    - process_total
    - process_thread
    - process_sleeping
#    - cpu_use_percent
    - cpu_temp
    - docker_active
    - docker_cpu_use
    - docker_memory_use

# ##########################################################################
# Arlo
# ##########################################################################
- platform: arlo
  monitored_conditions:
    - captured_today
    - last_capture
    - total_cameras
    - battery_level
    - signal_strength

# ##########################################################################
# Time & Date
# ##########################################################################
- platform: time_date
  display_options:
    - 'time'
    - 'date'

# ##########################################################################
# Weather
# ##########################################################################
- platform: darksky
  api_key: !secret dark_sky_api_key
  forecast:
    - 0
  language: de
  monitored_conditions:
    - summary
    - icon
    - precip_type
    - precip_intensity
    - precip_probability
    - precip_accumulation
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_gust
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_high
    - temperature_low
    - apparent_temperature_high
    - apparent_temperature_low
    - precip_intensity_max
    - uv_index
    - moon_phase
    - sunrise_time
    - sunset_time
    - nearest_storm_distance
    - nearest_storm_bearing

# ##########################################################################
# Netatmo
# ##########################################################################
- platform: netatmo
  station: Villa
  modules:
    Innenmodul:
      - temperature
      - humidity
      - co2
      - wifi_status
      - noise
      - pressure
    Aussenmodul:
      - temperature
      - humidity
      - min_temp
      - max_temp
      - battery_vp
      - rf_status

# ##########################################################################
# Gardena (DEV)
# ##########################################################################
- platform: gardena_smart
  username : !secret gardena_user
  password : !secret gardena_password
- platform: template
  sensors:
    sileno_last_online:
      friendly_name: "Sileno zuletzt online"
      value_template: "{{ states.sensor.sileno_city.attributes.last_online }}"
    sileno_battery_level:
      friendly_name: "Sileno Batterie"
      value_template: "{{ states.sensor.sileno_city.attributes.battery_level }}"
      unit_of_measurement: '%'
    sileno_charge_cycles:
      friendly_name: "Sileno Ladezyklen"
      value_template: "{{ states.sensor.sileno_city.attributes.charge_cycles }}"
      unit_of_measurement: ''
    sileno_collisions:
      friendly_name: "Sileno Kollisionen"
      value_template: "{{ states.sensor.sileno_city.attributes.collisions }}"
      unit_of_measurement: ''
    sileno_cutting_time:
      friendly_name: "Sileno Mähzeit total"
      value_template: "{{ states.sensor.sileno_city.attributes.cutting_time }}"
      unit_of_measurement: hours
    sileno_error:
      friendly_name: "Sileno Fehler"
      value_template: "{{ states.sensor.sileno_city.attributes.error }}"
    sileno_error_time:
      friendly_name: "Sileno Fehlerzeitpunkt"
      value_template: "{{ states.sensor.sileno_city.attributes.error_time }}"
    sileno_next_start_time:
      friendly_name: "Sileno Nächster Start"
      value_template: "{{ states.sensor.sileno_city.attributes.next_start }}"
    sileno_next_start_source:
      friendly_name: "Sileno Nächster Startort"
      value_template: "{{ states.sensor.sileno_city.attributes.next_source_for_start }}"

# ##########################################################################
# Measure Switches
# ##########################################################################
- platform: template
  sensors:
    pwr_dehumidifier:
      friendly_name: "Luftentfeuchter Leistung"
      unit_of_measurement: 'W'
      value_template: '{% if states.switch.luftentfeuchter %}{{ states.switch.luftentfeuchter.attributes.current_power_w }}{% else %}Off{% endif %}'
- platform: template
  sensors:
    pwr_dehumidifier_today:
      friendly_name: "Luftentfeuchter Leistung heute"
      unit_of_measurement: 'kWh'
      value_template: '{% if states.switch.luftentfeuchter %}{{ states.switch.luftentfeuchter.attributes.today_energy_kwh }}{% else %}Off{% endif %}'

- platform: template
  sensors:
    pwr_washingmachine:
      friendly_name: "Waschmaschine Leistung"
      unit_of_measurement: 'W'
      value_template: '{% if states.switch.waschmaschine %}{{ states.switch.waschmaschine.attributes.current_power_w }}{% else %}Off{% endif %}'
- platform: template
  sensors:
    pwr_washingmachine_today:
      friendly_name: "Waschmaschine Leistung heute"
      unit_of_measurement: 'kWh'
      value_template: '{% if states.switch.waschmaschine %}{{ states.switch.waschmaschine.attributes.today_energy_kwh }}{% else %}Off{% endif %}'

- platform: template
  sensors:
    pwr_dryer:
      friendly_name: "Trockner Leistung"
      unit_of_measurement: 'W'
      value_template: '{% if states.switch.trockner %}{{ states.switch.trockner.attributes.current_power_w }}{% else %}Off{% endif %}'
- platform: template
  sensors:
    pwr_dryer_today:
      friendly_name: "Trockner Leistung heute"
      unit_of_measurement: 'kWh'
      value_template: '{% if states.switch.trockner %}{{ states.switch.trockner.attributes.today_energy_kwh }}{% else %}Off{% endif %}'

- platform: template
  sensors:
    pwr_light_cellar:
      friendly_name: "Licht Keller Leistung"
      unit_of_measurement: 'W'
      value_template: '{% if states.light.keller %}{{ states.light.keller.attributes.power_consumption }}{% else %}Off{% endif %}'
- platform: template
  sensors:
    pwr_light_cellar_today:
      friendly_name: "Licht Keller Leistung heute"
      unit_of_measurement: 'kWh'
      value_template: '{% if states.light.keller %}{{ states.light.keller.attributes.energie_counter_kwh }}{% else %}Off{% endif %}'

# ##########################################################################
# Homematic
# ##########################################################################
- platform: template
  sensors:
    climate_living_room_level:
      friendly_name: "Wohnzimmer Heizung Niveau"
      value_template: '{{ states.climate.living_room.attributes.level }}'
      unit_of_measurement: '%'
- platform: template
  sensors:
    climate_living_room_current_temperature:
      friendly_name: "Wohnzimmer Heizung Temperatur aktuell"
      value_template: '{{ states.climate.living_room.attributes.current_temperature }}'
      unit_of_measurement: '°C'
- platform: template
  sensors:
    climate_living_room_temperature:
      friendly_name: "Wohnzimmer Heizung Temperatur soll"
      value_template: '{{ states.climate.living_room.attributes.temperature }}'
      unit_of_measurement: '°C'

- platform: template
  sensors:
    climate_living_room_sliding_door_level:
      friendly_name: "Wohnzimmer Heizung Schiebetür Niveau"
      value_template: '{{ states.climate.living_room_sliding_door.attributes.level }}'
      unit_of_measurement: '%'
- platform: template
  sensors:
    climate_living_room_sliding_door_current_temperature:
      friendly_name: "Wohnzimmer Heizung Schiebetür Temperatur aktuell"
      value_template: '{{ states.climate.living_room_sliding_door.attributes.current_temperature }}'
      unit_of_measurement: '°C'
- platform: template
  sensors:
    climate_living_room_sliding_door_temperature:
      friendly_name: "Wohnzimmer Heizung Schiebetür Temperatur soll"
      value_template: '{{ states.climate.living_room_sliding_door.attributes.temperature }}'
      unit_of_measurement: '°C'

- platform: template
  sensors:
    climate_entrance_level:
      friendly_name: "Eingang Heizung Niveau"
      value_template: '{{ states.climate.entrance.attributes.level }}'
      unit_of_measurement: '%'
- platform: template
  sensors:
    climate_entrance_current_temperature:
      friendly_name: "Eingang Heizung Temperatur aktuell"
      value_template: '{{ states.climate.entrance.attributes.current_temperature }}'
      unit_of_measurement: '°C'
- platform: template
  sensors:
    climate_entrance_temperature:
      friendly_name: "Eingang Heizung Temperatur soll"
      value_template: '{{ states.climate.entrance.attributes.temperature }}'
      unit_of_measurement: '°C'

- platform: template
  sensors:
    climate_amelie_level:
      friendly_name: "Amelie Heizung Niveau"
      value_template: '{{ states.climate.amelie.attributes.level }}'
      unit_of_measurement: '%'
- platform: template
  sensors:
    climate_amelie_current_temperature:
      friendly_name: "Amelie Heizung Temperatur aktuell"
      value_template: '{{ states.climate.amelie.attributes.current_temperature }}'
      unit_of_measurement: '°C'
- platform: template
  sensors:
    climate_amelie_temperature:
      friendly_name: "Amelie Heizung Temperatur soll"
      value_template: '{{ states.climate.amelie.attributes.temperature }}'
      unit_of_measurement: '°C'

- platform: template
  sensors:
    climate_marlene_level:
      friendly_name: "Marlene Heizung Niveau"
      value_template: '{{ states.climate.marlene.attributes.level }}'
      unit_of_measurement: '%'
- platform: template
  sensors:
    climate_marlene_current_temperature:
      friendly_name: "Marlene Heizung Temperatur aktuell"
      value_template: '{{ states.climate.marlene.attributes.current_temperature }}'
      unit_of_measurement: '°C'
- platform: template
  sensors:
    climate_marlene_temperature:
      friendly_name: "Marlene Heizung Temperatur soll"
      value_template: '{{ states.climate.marlene.attributes.temperature }}'
      unit_of_measurement: '°C'

- platform: template
  sensors:
    climate_bedroom_level:
      friendly_name: "Schlafzimmer Heizung Niveau"
      value_template: '{{ states.climate.bedroom.attributes.level }}'
      unit_of_measurement: '%'
- platform: template
  sensors:
    climate_bedroom_current_temperature:
      friendly_name: "Schlafzimmer Heizung Temperatur aktuell"
      value_template: '{{ states.climate.bedroom.attributes.current_temperature }}'
      unit_of_measurement: '°C'
- platform: template
  sensors:
    climate_bedroom_temperature:
      friendly_name: "Schlafzimmer Heizung Temperatur soll"
      value_template: '{{ states.climate.bedroom.attributes.temperature }}'
      unit_of_measurement: '°C'

- platform: template
  sensors:
    climate_studio_level:
      friendly_name: "Studio Heizung Niveau"
      value_template: '{{ states.climate.studio.attributes.level }}'
      unit_of_measurement: '%'
- platform: template
  sensors:
    climate_studio_current_temperature:
      friendly_name: "Studio Heizung Temperatur aktuell"
      value_template: '{{ states.climate.studio.attributes.current_temperature }}'
      unit_of_measurement: '°C'
- platform: template
  sensors:
    climate_studio_temperature:
      friendly_name: "Studio Heizung Temperatur soll"
      value_template: '{{ states.climate.studio.attributes.temperature }}'
      unit_of_measurement: '°C'

- platform: template
  sensors:
    climate_fitness_level:
      friendly_name: "Fitness Heizung Niveau"
      value_template: '{{ states.climate.fitness.attributes.level }}'
      unit_of_measurement: '%'
- platform: template
  sensors:
    climate_fitness_current_temperature:
      friendly_name: "Fitness Heizung Temperatur aktuell"
      value_template: '{{ states.climate.fitness.attributes.current_temperature }}'
      unit_of_measurement: '°C'
- platform: template
  sensors:
    climate_fitness_temperature:
      friendly_name: "Fitness Heizung Temperatur soll"
      value_template: '{{ states.climate.fitness.attributes.temperature }}'
      unit_of_measurement: '°C'

# ##########################################################################
# Sun Elevation
# ##########################################################################
- platform: template
  sensors:
    sun_elevation:
      friendly_name: "Sonnenstand Horizont"
      value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      unit_of_measurement: 'degrees'

# ##########################################################################
# Weather Warnings
# ##########################################################################
- platform: dwd_weather_warnings
  region_name: Erding

# ##########################################################################
# Scraper
# ##########################################################################

# ##########################################################################
# Media Players
# ##########################################################################
#- platform: plex
#  host: !secret plex_ip
#  port: !secret plex_port
#  name: Plex

# ##########################################################################
# Internet speed
# ##########################################################################
#- platform: speedtestdotnet
#  monitored_conditions:
#    - ping
#    - download
#    - upload
#  scan_interval:
#    minutes: 30

# ##########################################################################
# Harmony
# ##########################################################################
- platform: template
  sensors:
    harmony_activity:
      friendly_name: "Harmony Activity"
      value_template: '{{ states.remote.living_room.attributes.current_activity }}'

# ##########################################################################
# MQTT iPhone Sensors
# ##########################################################################
- platform: mqtt
  state_topic: owntracks/markus/D79762C2-B7FF-4E48-8B3D-5BDDA255521F
  name: "Markus iPhone 8 Akku"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'
      
- platform: mqtt
  state_topic: owntracks/markus2/7D4E4247-B276-4807-B766-9A1FEDC2E1C7
  name: "Markus iPhone 7 Akku"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

- platform: mqtt
  state_topic: owntracks/magda/5B9E4342-2EF1-431E-AEE2-D85A7E9DB173
  name: "Magda iPhone 8 Akku"
  unit_of_measurement: "%"
  value_template: '{{ value_json.batt }}'

# ##########################################################################
# Zigbee Bridge State
# ##########################################################################
- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless

# ##########################################################################
# Special HASS related sensors
# ##########################################################################
- platform: version
  name: HA Installed Version
  scan_interval: 86400

- platform: command_line
  name: "HA Uptime"
  command: echo "$(($(date +%s) - $(date -d "$(head -n1 /config/home-assistant.log | cut -d' ' -f-2)" +%s)))"
  scan_interval: 720
  value_template: >-
    {% set uptime = value | int %}
    {% set seconds = uptime % 60 %}
    {% set minutes = ((uptime % 3600) / 60) | int %}
    {% set hours = ((uptime % 86400) / 3600) | int %}
    {% set days = (uptime / 86400) | int %}
    {%- if days > 0 -%}
      {%- if days == 1 -%}
        1 day
      {%- else -%}
        {{ days }} days
      {%- endif -%}
      {{ ', ' }}
    {%- endif -%}
    {%- if hours > 0 -%}
      {%- if hours == 1 -%}
        1 hour
      {%- else -%}
        {{ hours }} hours
      {%- endif -%}
      {{ ', ' }}
    {%- endif -%}
    {%- if minutes > 0 -%}
      {%- if minutes == 1 -%}
        1 minute
      {%- else -%}
        {{ minutes }} minutes
      {%- endif -%}
    {%- endif -%}
