# ##########################################################################
# Flux
# ##########################################################################
#- platform: flux
#  lights:
#    - light.schlafzimmer
#    - light.studio
#  name: Fluxer
#  start_time: '6:00'
#  stop_time: '23:00'
#  start_colortemp: 4000
#  sunset_colortemp: 3000
#  stop_colortemp: 1900
#  brightness: 200
#  disable_brightness_adjust: True
#  mode: xy
#  transition: 30
#  interval: 60

# ##########################################################################
# Robonect
# ##########################################################################
#- platform: mqtt
#  name: "Robonect Switch"
#  state_topic: "robonect/controlbedroom/switch1"
#  command_topic: "home/bedroom/switch1/set"
#  availability_topic: "home/bedroom/switch1/available"
#  payload_on: "ON"
#  payload_off: "OFF"
#  state_on: "ON"
#  state_off: "OFF"
#  optimistic: false
#  qos: 0
#  retain: true

# ##########################################################################
# Zigbee2mqtt
# ##########################################################################
- platform: mqtt
  name: "Zigbee2mqtt1 Main join"
  state_topic: "zigbee2mqtt1/bridge/config/permit_join"
  command_topic: "zigbee2mqtt1/bridge/config/permit_join"
  payload_on: "true"
  payload_off: "false"

- platform: mqtt
  name: "Zigbee2mqtt2 Main join"
  state_topic: "zigbee2mqtt2/bridge/config/permit_join"
  command_topic: "zigbee2mqtt2/bridge/config/permit_join"
  payload_on: "true"
  payload_off: "false"

# ##########################################################################
# REST Switches
# ##########################################################################
